Added Saving functionality.
madras-simulator/baselines pull request #3
Opened 2018-11-30 05:22 UTC by rudrasohan

Why?
There was no previous option to support the saving of trained networks(ddpg). Hence to add that functionality.

What?
Built a saving function where you can manually specify a dir for the network to save and can also load the desired model back.

Testing

_For saving:_
Specify the path of the save directory in the field `specify/path` in the `ddpg.py`. Then run the code as usual. `python -m baselines.run --alg='ddpg' --env='Madras-v0'`

_For loading:_
`python -m baselines.run --alg='ddpg' --env='Madras-v0' --load_path=/specify/path/to/save/file`

NOTE: 
The save function takes in a dir whereas the load function takes in a file.
This PR also includes #1 as that will be required for madras-env to be working.

2018-11-30 13:50 UTC, buridiaditya commented on baselines/ddpg/ddpg.py
> +          save_path = '<specify/path>'
Missed a comma

2018-11-30 13:51 UTC, buridiaditya commented on baselines/ddpg/ddpg.py
> +            os.mkdirs(logdir,exist_ok=True)
Error in python mkdirs does not exist

2018-12-01 10:57 UTC, buridiaditya requested changes
Error :
`Traceback (most recent call last):
  File "/usr/home/brahma/anaconda3/envs/torcs/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/home/brahma/anaconda3/envs/torcs/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/home/brahma/BURIDI/MADRAS/baselines/baselines/run.py", line 226, in <module>
    main(sys.argv)
  File "/usr/home/brahma/BURIDI/MADRAS/baselines/baselines/run.py", line 198, in main
    model, env = train(args, extra_args)
  File "/usr/home/brahma/BURIDI/MADRAS/baselines/baselines/run.py", line 81, in train
    **alg_kwargs
  File "/usr/home/brahma/BURIDI/MADRAS/baselines/baselines/ddpg/ddpg.py", line 98, in learn
    agent.load(load_path)
TypeError: 'NoneType' object is not callable`

Recreation:
1. Ran the training with save path mentioned it created files with epoch numbers.
2. Load any of the file to recreate the error. Loading using this command 
`python -m baselines.run --alg='ddpg' --env='Madras-v0' --load_path='file_path'` 
and also tried directly setting the load_path in the code.

2018-12-05 15:57 UTC, buridiaditya approved these changes

2018-12-05 15:57 UTC, merged

2018-12-07 06:05 UTC, hari-sikchi commented
1. If you select the noise type as parameter noise, then there is a variable in agent called agent.param_noise.current_stddev, which is not a tensor, so when you save the trained agent and do the restoring, this parameter will not be recovered.
2.  If you save/restore the policy as in #162, if normalize_observations=True (the default value), then the mean/std used for normalization will not be recoverable.

Restating some issues here for convenience. @rudrasohan